### ISSUE TITLE
Discussion: binary file handling

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/UT3Vehicles#104]
I'm still wondering as to what would be the best policy to handle binary files here. Facts are:

- Git is not made for binaries. It is really bad at them and on editing will store all instances of all files that were ever in the repo. This makes downloads real slow and GitHub will eventually refuse to put more files in altogether.
- If the binaries can remain unchanged, that is one less file that people need to update in order to avoid version mismatches.
- Some things that can be changed in binaries can also be done in code (scale, collision, combiners, shaders, ...).
- Some things cannot (vehicle centre-of-mass is defined by the `(0,0,0)` point in the mesh).
- Ideally source code and binaries should be kept in sync.

Thus, ideally binaries would never change. If possible, code should be used instead of changing binaries. However, looks like they need to change somewhat (in some cases, like textures, it's much more convenient to do via UI than code).

The other option would be to store all binaries in one central repository, and then have a link or a script to download them all as-needed. However, GitHub is nice in that reviews are possible. If we were to use e.g. HellDragon's Google Drive for it, nobody else would be able to update the binaries.

I see two potential solutions:
- Look for something that does allow several people to collaborate on in a review manner. Perhaps someone has suggestions for potential services here. For instance Google Drive allows collaboration on files, but not staging files for review.
- Make a download script with each file on its own line. Changes to the URLs in the script could be submitted as pull requests.

I do like the sound of the second solution, though it would probably not be cross-platform. A bash script with wget commands would work nicely on Linux though, which would be fine for me and @100GPing100 I suppose. Otherwise the file could be a CSV or other type of plain text and the script would parse it, with one script for Windows and one for Linux.

In the mean while, I'm using the `Binary file` tag to track issues where binary files have been mentioned (note that they can also be closed, this does not invalidate the fact that there may be binary files there) and I'm trying to add `Binary requirement` to pulls that modify code to depend on binary files that have changed (again they can be closed).

Suggestions would be highly appreciated!

**Comment by GreatEmerald** [comment]
Also note that Google Drive URLs don't work directly in `wget`. The closest thing is to conver the URLs into Google API and then use `--content-disposition`, but for me that results in a filename that is doubled:
```bash
$ wget --content-disposition "https://drive.google.com/uc?export=download&confirm=LJ_a&id=1cDv2_FcH72_1rgIjBt5zdTU_pSRpkrqe"
$ ls
UT3VH_SPMA_Anims.ukxUT3VH_SPMA_Anims.ukx
```
That's a lot of trouble just to download a file. Other cloud providers are much easier to work with (and in theory I could also just host the files on my website).

**Comment by HellDragon-HK** [comment]
"Some things cannot (vehicle centre-of-mass is defined by the (0,0,0) point in the mesh)."

PrePivot does work in the code, the only thing I've had to change that I don't know how to code is the collision boxes (X Y & Z types), UT3 code does it but UT2004 won't compile it and so far I can't recall ever seeing a collision box in the code anywhere...just collision height and radius which I don't think will work.

I don't really understand much else of what is said here but if it would help I can make a new folder on my G-Drive and have 1 link directly to it so everything is visible at once

**Comment by GreatEmerald** [comment]
The code only handles collision cylinders. Technically the editor can create a collision box or use per-surface (the most accurate) collision. I don't recall which collision type is used in which case. Either way you should see it in in-game with the `show collision` command.

No, the problem with Google Drive is that you can edit it (because it's yours) and we can't. I'd prefer if files were submitted by something like pull requests, but we can't use git for binaries. So ideally we'd use some other cloud technology to update files and just add links to each file in the git repository, without putting the files themselves here.

**Comment by HellDragon-HK** [comment]
I've used ShowColliision in-game several times, and usually collision boxes are shown, oddly though whenver I broke the Goliath & SPMA with trying to change their scale they showed no collision with this command yet had a cylinder around them that I couldn't get past

"No, the problem with Google Drive is that you can edit it (because it's yours) and we can't."

Even if I set it to anyone can edit?

**Comment by GreatEmerald** [comment]
Hm, but you can see cylinders around other objects with it?

Yes, even if you set that everyone can edit, there will be a problem because we won't be able to review edits like we can do with code.

**Comment by HellDragon-HK** [comment]
Not vehicles, just landscape pieces, the only collision I've been able to see with vehicles is boxes, cylinders are invisible and just there if the boxes are not...hard to explain

Alright then I'll step aside at let you and GP figure out the binary issue

**Comment by 100GPing100** [comment]
Given all the requirements I'd propose the usage of a repository specifically for the binary files (since these are not expected to change much) together with a script in this repository that would download the binary files from that repository.

- A binary pull request would be made in this new repository
- A corresponding pull request would exist here with a reference to the binary pull request
- This pull request here would update the download script with the link to the new commit on the binary repository
- Once the binary pull request would be accepted, the pull request here could be accepted to as to update the binary download link

For point number two: it is possible to cross reference in the format `user/repository#99`.

This would ensure that the correct versions would be used. It would be just a matter of creating this download script that would clone the binary repository (if not already cloned) updated refs and download a specific commit (this specific commit is what the pull request here changes).

**Comment by GreatEmerald** [comment]
So you mean to use a separate git repository for binaries? That would work nicely with git submodules, so we wouldn't even need a script for that, but that doesn't solve the issue of git being real bad at binaries and GitHub not really giving a lot of space for them to begin with. It's possible to remove old versions of the binaries, but it includes rewriting the entire history, and that's not great.

**Comment by 100GPing100** [comment]
What about using [Git Large File Storage](https://git-lfs.github.com/)?

**Comment by GreatEmerald** [comment]
I'll go over pros and cons.

Submodule approach pros:
- Easy to use, no changes in software needed
- Can control binaries in a more fine-grained manner (using branches etc.) than when the binaries are in the same tree

Cons:
- Subject to the same GitHub limitations
- Requires constant maintenance to purge old versions
- Reviews have to happen in a separate repository, effectively two reviews per pull request
- No fine-grained control over each file: either the whole repository submodule is updated or nothing at all, which may cause sync problems.

In short, it's simple but doesn't help that much.

git-lfs (and others, like git-annex) pros:
- Reviews can happen like normal pull requests
- Storage is external, no limits
- Versioning still applies, can revert

Cons:
- Requires additional software
- Can only be used via command line
- Unknown how GitHub as backend works, or how to make new backends

In short, it potentially solves the problem, but would add a whole lot of complexity which is a barrier to entry. For instance, HellDragon currently uses just the GitHub web interface, so this would exclude all his contributions (or require us to do more work on our side).

I'm still favouring the wget script solution (that's about how Epic are doing it nowadays too). Pros:
- Storage can be arbitrary (even different backends)
- Fine-grained per-file control
- Pull requests work as usual
- Simple enough for everyone to understand
- Can place files outside the mod directory

Cons:
- Platform-dependent. We'll need a Bash script and also a CMD script on Windows.
- Dead links may be an issue.

To expand a bit on that, the file definitions could be simple CSV files in this schema:

| URL | Directory | Filename | `wget` options |
|------|--------------|--------------|-------------------|
| https://drive.google.com/uc?export=download&id=1QSeKP6KxkT9vBNyptGE7ouPl76W1EL-C | Animations | UT3VH_Scorpion_Anims.ukx | --content-disposition |

Parsing that into `wget --content-disposition -OAnimations/UT3VH_Scorpion_Anims.ukx https://drive.google.com/uc?export=download&id=1QSeKP6KxkT9vBNyptGE7ouPl76W1EL-C` would be easy for both Bash (via `cut`/`awk`) and (I assume) CMD. Filling it this form manually wouldn't be difficult either. Of course, on Windows you'd still need to have wget installed, else the options wouldn't be useful.

**Comment by 100GPing100** [comment]
From what I've seen `git-lfs` works with command line, web interface and even the GitHub desktop app, but I too am a fan of the `wget` script. The only thing that gets me concerned about the `wget` method would be the dead links and there would be no version control. However, trusting the person who uploads the files I don't see how this could be an issue.

Later on once the mod "stagnates" (in the sense of becoming stable) we'll need to make sure we get some reliable storage location (some link we'll have some certainty will not go down so easily/quickly).

Regarding the script, we could also have support for multiple mirrors, that would help with dead links.

**Comment by GreatEmerald** [comment]
Hm, interesting, I looked a bit more at git-lfs, but while it does work with the command line and the GitHub app, it doesn't look like it would work through the web interface (uploading would upload the whole file, not to LFS, and viewing an LFS file shows the pointer).

Well, with the `wget` method version control would work in the way that the previous files are still available via previous URLs. We just need to make sure that files are not replaced but rather new ones are added, and that the previous ones are not deleted very quickly.

Yes, obviously once we reach the RC milestone and there's a new release, the files will all be assembled in one place, and the script would be updated to simply pull an entire tarball for that release.

Multiple mirrors would help, but while in the middle of development they wouldn't be all that useful. But of course the script should be smart enough to figure out when to replace the file and when not to. Maybe add an extra field for the sha256sum or so?

**Comment by 100GPing100** [comment]
Yes some kind of checksum should be enough for knowing when to download the file, I'd say something along the lines of

```lua
for entry in csv do
    if checksum(entry.directory .. '/' .. entry.filename) != entry.checksum then
        remove(entry.directory .. '/' .. entry.filename)
        download(entry)
   end
end
```

**Comment by GreatEmerald** [comment]
Yeap. I'm starting to work on this right now, since there are a lot of binary files pending. I'll keep you posted on the progress, since the whole repository will have to be rewritten once it's done, and only then can pull requests that depend on binary changes be accepted.

**Comment by GreatEmerald** [comment]
All right, here's the initial implementation: https://github.com/GreatEmerald/UT3Vehicles/commit/3b2b867f209f5ef58bd7e506bf8ee874eef24827
@100GPing100: You can check whether this works for you (note that this may overwrite `UT3VH_Scorpion_Anims.ukx` with something that is probably not current)
@HellDragon-HK: Check out https://github.com/GreatEmerald/UT3Vehicles/blob/master/Binaries.csv: for every binary that you want to change, you'll need to fill out a line of this table. If you press `Raw` you can see that it is actually a plain text file, with each field separated by commas. For files that already exist you'd need to update the existing lines, for new files you'd need to put in new lines. You can do that either by using a plain text editor, or a spreadsheet editor.

**Comment by 100GPing100** [comment]
@GreatEmerald Works like a charm! Now we only need to get all the binaries in there

**Comment by GreatEmerald** [comment]
Yeap, that and and clearing out all the current binaries, which I believe will require a rebase of all pull requests. We'll also need an equivalent script for Windows eventually.

**Comment by 100GPing100** [comment]
Well for windows, a temporary solution is to install `Bash for Windows`, would work, but of course it's just a "fix" (that is if it even comes with `wget` or if it can be installed). It's kinda important to get a Windows version because all of the binary updates are done on Windows, technically the binary files are more important for Windows (even tho we do need them to compile the code and run the mod).

**Comment by GreatEmerald** [comment]
Yea. WSL (Windows Subsystem for Linux, or as I like to call it, LINE) should indeed work as it downloads Ubuntu, but it's Windows 10 exclusive. Otherwise mingw should also work, provided `wget` is installed; this seems to be pretty easy to do when you have Git for Windows, which is required in any case: https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058

**Comment by GreatEmerald** [comment]
It would also be nice to check if `sha256sum` works in Git Bash. It should, since it's part of OpenSSL, but would be nice to confirm.

**Comment by GreatEmerald** [comment]
@100GPing100 I see there are some directories that seem unused: `Animations/Unused`, `Sounds/UT3Nightshade` (there's `UT3A_Vehicle_Nightshade.uax` which I assume has these?), `UT3Viper_`. Can I remove those?

**Comment by GreatEmerald** [comment]
Oh, also, to add redundancy in case of broken links, we can simply add redundant entries. The script will recheck the checksums, but since they should match, the second URL will be ignored if the first one succeeds in downloading. If the first one fails, then the script moves on to the second and downloads that.

**Comment by GreatEmerald** [comment]
There's also `Textures/SPMASmoke.dds`, not sure what that's about. Probably Wormbo's, he likes not putting files into packages. But that won't work with the script, as it puts files directly into the needed folders. for now I'll keep it in the repository, but I'll remove it once that gets put into some package.

**Comment by HellDragon-HK** [comment]
SPMAsmoke missing was something I was having as an error on compile when we first started this, I assumed you had to add it in

**Comment by GreatEmerald** [comment]
All right, I put all of the files that have not changed into `Binaries.csv` in commit https://github.com/GreatEmerald/UT3Vehicles/commit/ca0435ebb2333a652630f8f53b969748487c5007. Please test. If this is OK and the rest is integrated from pull #164 I will purge binaries from the repository.

**Comment by HellDragon-HK** [comment]
We don't want to lose what's in the unused folder though right? I don't see Darkwalker and Scavenger in that commit for example

**Comment by HellDragon-HK** [comment]
Btw I didn't scale those , was I supposed to?

**Comment by GreatEmerald** [comment]
Hm, I don't know. It's unused. Maybe I'll pack all unused files and put them into an archive somewhere for reference, but not have people download this every time through the script.

No, you're not supposed to do the scaling yet. Once you do you'll want to submit an update to `Binaries.csv`.

**Comment by 100GPing100** [comment]
@GreatEmerald Yes now that there are the sound packages those files are not needed anymore. How it worked before was that the sound package would be created at compile time using some `#exec` statements.

**Comment by GreatEmerald** [comment]
OK, great. Everything seems fine on my end, so I'll proceed with purging binaries now. We'd need someone to test the script on Windows too, but it's not urgent.

Note that once I purge them, every single branch will have to be rebased on the new master! You cannot merge commits, you must rebase, or else you'll put all the binaries right back and I won't accept such pull requests. See https://git-scm.com/book/en/v2/Git-Branching-Rebasing.

**Comment by GreatEmerald** [comment]
All right, since there's still a bunch of pull requests that are not dealt with, I'll wait until tomorrow morning before purging binaries. If there are still pull requests that are not dealt with at the time, they will need to be rebased.

**Comment by GreatEmerald** [comment]
@100GPing100: Oh yes, and for those who use the git command line, after I purge the binaries do not use `git pull`, use `git pull --rebase` (or `git fetch` + `git rebase GreatEmerald/master`), else you'll find all commits doubled because you won't purge out the binaries from your local history.

**Comment by GreatEmerald** [comment]
Hm, I'll be a bit busy right now, so I'll wait until the evening to purge the binaries. I'm also not entirely certain how rebasing between forks works, something to look into in the mean while perhaps. In case things go wrong, the forks can be deleted and reforked, but in that case you might want to keep any commits you want to keep as patches via `git patch`.

**Comment by GreatEmerald** [comment]
All right, proceeding with the binary purge.

**Comment by GreatEmerald** [comment]
Binary purge complete! You may now rebase everything (or delete the forks and recreate them).

**Comment by GreatEmerald** [comment]
FIY: if you need the unused files, I put them into https://cloud.greatemerald.eu/s/fxcvDfEKYmmxTB6.

**Comment by HellDragon-HK** [comment]
Sorry about commenting on a closed issue but I didn't get any e-mails anybody was even around today :S
