### ISSUE TITLE
Team-coloured headlight coronas

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/UT3Vehicles#110]
In UT3, headlights are team-coloured. In UT2004, they are team-coloured too, but you wouldn't know if you didn't look real closely at them! This effect should be more pronounced.

In UT2004, this is handled by the ONSHeadlightCorona class: http://greatemerald.xmpcommunity.com/uncodex/UT2004/Source_onslaught/onsheadlightcorona.html#4 However, these values are hardcoded, and the class of the headlight coronas is hardcoded too, which is a problem.

Several approaches could be used in this case:

- In each vehicle, replace the bit of code that spawns the `ONSHeadlightCorona` with one that spawns our custom `UT3HeadlightCorona` with the correct values;
- Use `CheckReplacement()` in a mutator to replace all `ONSHeadlightCorona`s with `UT3HeadlightCorona`s;
- Add new code to each vehicle to set the hue and saturation manually after each team switch (`TeamChanged`).

One big difference between these approaches would be network compatibility. The default headlight has `RemoteRole=ROLE_None`, which means it is completely client-side. I'm not sure if destroying it would be replicated or not... If not, you'd get two headlights on top of one another when using approach 2. Approach 3 would work as long as the code is run by the clients as well (it should be). Approach 1 would always work, but it requires copy-pasting a lot of code to each vehicle.

I'd probably go for option 3, and if it doesn't work, for option 1.

**Comment by HellDragon-HK** [comment]
Speaking of UT3HeadlightCorona, here is the uc I was trying to use https://drive.google.com/open?id=1BBPpls85AuQW8tSwLjAY5y3yEPo_09NE basically a direct copy of the original but with Alex's color suggestions

"In each vehicle, replace the bit of code that spawns the ONSHeadlightCorona with one that spawns our custom UT3HeadlightCorona with the correct values;"

This is what I tried, and the effect works but it's always turned on even when empty and doesn't disappear on death either

**Comment by GreatEmerald** [comment]
That is strange, it ought to work, because UT3HeadlightCorona is an ONSHeadlightCorona (so it should be spawned and destroyed correctly with the existing code). You should put this up as a pull request so I can check for any things that may be missing.

**Comment by HellDragon-HK** [comment]
This class or the vehicle I tried to change, which I don't have the full changes anymore as it went badly and I reverted but I think I download the test file I sent Alex of where it worked without adversely affecting the vehicle

**Comment by HellDragon-HK** [comment]
@GreatEmerald btw what corona textures are we going with,

For the Headlights you've had it set as FlareOY, default is usually FlashFlare1, I like the FlareOY but not sure how it will work with team colors since it's already yellow, also there is a huge difference in size appearance (and possibly even placement) between FlareOY and FlashFlare1

For the Brakelights you've had it on FlickerFlare which I like but at times it looks too small and there doesn't seem to be a scale option for the brakelights strangely unless it pulls from the headlights scale, again the default is usually FlashFlare1, also I've noticed FlickerFlare has little spikes of light in a star shape coming from it, FlashFlare does not, not sure which I prefer honestly

**Comment by GreatEmerald** [comment]
They should not be coloured, since we need to change the colour in code.

**Comment by HellDragon-HK** [comment]
The FlareOY on blue has a greenish look to it now that I've noticed

Alex hates FlashFlare1 saying it's harsh, so I'm not sure where to go here, try different flares or Alex maybe just make one?

**Comment by GreatEmerald** [comment]
Either works, whatever looks good.

**Comment by HellDragon-HK** [comment]
The corona changes appear to work on all vehicles so far, so only thing now is are we happy with the material texture & the colors?  If yes we can probably close this issue now right?

**Comment by GreatEmerald** [comment]
Yeap, this is now fixed.
