### ISSUE TITLE
Missing class 'UT3DmpType_ScorpionBlades'

### ISSUE THREAD

**Issue by 100GPing100** [GreatEmerald/UT3Vehicles#178]
https://github.com/GreatEmerald/UT3Vehicles/blob/f8c45fe389fd190439c17e5f03ce1e6e207fa23a/Classes/UT3Scorpion.uc#L159

https://github.com/GreatEmerald/UT3Vehicles/blob/f8c45fe389fd190439c17e5f03ce1e6e207fa23a/Classes/UT3Scorpion.uc#L189

Changed in https://github.com/GreatEmerald/UT3Vehicles/commit/2f52097b5cc03ee126f53dc8d11edb90428d22c5

To fix: Create the missing class

**Comment by GreatEmerald** [comment]
Fixed.
