### ISSUE TITLE
Missing class 'UT3DmgType_HellbenderCombo'

### ISSUE THREAD

**Issue by 100GPing100** [GreatEmerald/UT3Vehicles#180]
https://github.com/GreatEmerald/UT3Vehicles/blob/f8c45fe389fd190439c17e5f03ce1e6e207fa23a/Classes/UT3HBShockBall.uc#L17

This class does not yet exists, thus prevents compilation. Changed in: https://github.com/GreatEmerald/UT3Vehicles/commit/69cc866193289036c1d804ad58c82f7e20f9c563

**Comment by HellDragon-HK** [comment]
I know I uploaded that.....what happened to it?

**Comment by 100GPing100** [comment]
@HellDragon-HK Might have been lost at some point, same for #178

**Comment by HellDragon-HK** [comment]
@Unre-Alex is now saying we have duplicates yet you say they are missing?????  I'm 200% lost on what's going on.

**Comment by GreatEmerald** [comment]
Fixed.
